version: '3.8'
services:
  db:
    image: postgres:15
    container_name: vital-db
    environment:
      POSTGRES_USER: ankit
      POSTGRES_PASSWORD: password
      POSTGRES_DB: vitalsync_db
    ports:
      - "5432:5432"

  redis:
    image: redis:alpine
    container_name: vital-redis
    ports:
      - "6379:6379"