# NewsNest Spring Boot Configuration
server.port=8080
spring.application.name=news-service
# Database Config
spring.datasource.url=jdbc:postgresql://localhost:5432/newsnest_spring
spring.datasource.username=newsnest_user
spring.datasource.password=newsnest123
# Isko 'update' hi rakho kyunki table pehle hi ban chuki hai
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
# Open-in-view fix
spring.jpa.open-in-view=false
# API Config
news.api.key=cc9c209a536d43efbd2707e1d2c53424
news.api.url=https://newsapi.org/v2